### ISSUE TITLE
Great Repo but question

### ISSUE THREAD

**Issue by pastorlibre** [pauld-splunk/aws-s3-sqs-lambda#2]
Hi, first of all thank you for this... I have struggled getting AWS Data into Splunk. I followed your instructions and have a questions do I still need to set up the actual events to go into the S3 bucket? Such as Config, Cloudtrail, VPC or will the Lambda configure those as well? If so do I have to exectute the Lambda in some way? I have it deployed so just wandering..  This part is pretty new to me so its quite Greek LOL Thank you for any help

**Comment by pauld-splunk** [comment]
hi @pastorlibre. Yes, you have to get the configuration of events into the S3 bucket done first - for example, using Control Tower, or just go into each of the services and point them to that bucket. The lambda you have here is only there to "split" out the sources into different inputs on the splunk side, and doesn't do anything with the initial service to get the data into that bucket. Hope that helps.
